services:
  db:
    image: postgres:15
    container_name: vsi_postgres
    environment:
      POSTGRES_DB: vsi_db
      POSTGRES_USER: vsi_user
      POSTGRES_PASSWORD: vsi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: