zones:
  - name: "zone_trottoir"
    coords:
      - [150, 180]
      - [500, 180]
      - [500, 360]
      - [150, 360]

  - name: "zone_escalier"
    coords:
      - [0, 180]
      - [150, 180]
      - [150, 360]
      - [0, 360]