zones:
- coords:
  - - 13
    - 50
  - - 277
    - 219
  - - 276
    - 355
  - - 9
    - 356
  - - 10
    - 56
  - - 12
    - 53
  name: zone_escalier
- coords:
  - - 290
    - 357
  - - 629
    - 357
  - - 627
    - 300
  - - 312
    - 197
  - - 289
    - 355
  name: zone_trottoir
